const ruLang = [
  {
    code: "Backquote",
    type: "letter",
    ru: ["ё", "Ё"],
    en: ["`", "~"],
  },
  {
    code: "Digit1",
    type: "number",
    ru: ["1", "!"],
    en: ["1", "!"],
  },
  {
    code: "Digit2",
    type: "number",
    ru: ["2", '"'],
    en: ["2", "@"],
  },
  {
    code: "Digit3",
    type: "number",
    ru: ["3", "№"],
    en: ["3", "#"],
  },
  {
    code: "Digit4",
    type: "number",
    ru: ["4", ";"],
    en: ["4", "$"],
  },
  {
    code: "Digit5",
    type: "number",
    ru: ["5", "%"],
    en: ["5", "%"],
  },
  {
    code: "Digit6",
    type: "number",
    ru: ["6", ":"],
    en: ["6", "^"],
  },
  {
    code: "Digit7",
    type: "number",
    ru: ["7", "?"],
    en: ["7", "&"],
  },
  {
    code: "Digit8",
    type: "number",
    ru: ["8", "*"],
    en: ["8", "*"],
  },
  {
    code: "Digit9",
    type: "number",
    ru: ["9", "("],
    en: ["9", "("],
  },
  {
    code: "Digit0",
    type: "number",
    ru: ["0", ")"],
    en: ["0", ")"],
  },
  {
    code: "Minus",
    type: "number",
    ru: ["-", "_"],
    en: ["-", "_"],
  },
  {
    code: "Equal",
    type: "number",
    ru: ["=", "+"],
    en: ["=", "+"],
  },
  {
    code: "Backspace",
    type: "backspace",
    ru: ["Backspace", "Backspace"],
    en: ["Backspace", "Backspace"],
  },
  {
    code: "Tab",
    type: "tab",
    ru: ["Tab", "Tab"],
    en: ["Tab", "Tab"],
  },
  {
    code: "KeyQ",
    type: "letter",
    ru: ["й", "Й"],
    en: ["q", "Q"],
  },
  {
    code: "KeyW",
    type: "letter",
    ru: ["ц", "Ц"],
    en: ["w", "W"],
  },
  {
    code: "KeyE",
    type: "letter",
    ru: ["у", "У"],
    en: ["e", "E"],
  },
  {
    code: "KeyR",
    type: "letter",

    ru: ["к", "К"],
    en: ["r", "R"],
  },
  {
    code: "KeyT",
    type: "letter",
    ru: ["е", "Е"],
    en: ["t", "T"],
  },
  {
    code: "KeyY",
    type: "letter",
    ru: ["н", "Н"],
    en: ["y", "Y"],
  },
  {
    code: "KeyU",
    type: "letter",
    ru: ["г", "Г"],
    en: ["u", "U"],
  },
  {
    code: "KeyI",
    type: "letter",
    ru: ["ш", "Ш"],
    en: ["o", "O"],
  },
  {
    code: "KeyO",
    type: "letter",

    ru: ["щ", "Щ"],
    en: ["o", "O"],
  },
  {
    code: "KeyP",
    type: "letter",
    ru: ["з", "З"],
    en: ["p", "P"],
  },
  {
    code: "BracketLeft",
    type: "letter",
    ru: ["х", "Х"],
    en: ["[", "{"],
  },
  {
    code: "BracketRight",
    type: "letter",
    ru: ["ъ", "Ъ"],
    en: ["]", "}"],
  },
  {
    code: "Backslash",
    type: "letter",
    ru: ["\\", "/"],
    en: ["\\", "|"],
  },

  {
    code: "CapsLock",
    type: "capsLock",
    ru: ["CapsLock", "CapsLock"],
    en: ["CapsLock", "CapsLock"],
  },
  {
    code: "KeyA",
    type: "letter",
    ru: ["ф", "Ф"],
    en: ["a", "A"],
  },
  {
    code: "KeyS",
    type: "letter",
    ru: ["ы", "Ы"],
    en: ["s", "S"],
  },
  {
    code: "KeyD",
    type: "letter",
    ru: ["в", "В"],
    en: ["d", "D"],
  },
  {
    code: "KeyF",
    type: "letter",
    ru: ["а", "А"],
    en: ["f", "F"],
  },
  {
    code: "KeyG",
    type: "letter",
    ru: ["п", "П"],
    en: ["g", "G"],
  },
  {
    code: "KeyH",
    type: "letter",
    ru: ["р", "Р"],
    en: ["h", "H"],
  },
  {
    code: "KeyJ",
    type: "letter",
    ru: ["о", "О"],
    en: ["j", "J"],
  },
  {
    code: "KeyK",
    type: "letter",
    ru: ["л", "Л"],
    en: ["k", "K"],
  },
  {
    code: "KeyL",
    type: "letter",
    ru: ["д", "Д"],
    en: ["l", "L"],
  },
  {
    code: "Semicolon",
    type: "letter",
    ru: ["ж", "Ж"],
    en: [";", '"'],
  },
  {
    code: "Quote",
    type: "letter",
    ru: ["э", "Э"],
    en: ["'", '"'],
  },
  {
    code: "Enter",
    type: "enter",
    ru: ["Enter", "Enter"],
    en: ["Enter", "Enter"],
  },
  {
    code: "ShiftLeft",
    type: "shiftLeft",
    ru: ["Shift", "Shift"],
    en: ["Shift", "Shift"],
  },
  {
    code: "KeyZ",
    type: "letter",
    ru: ["я", "Я"],
    en: ["z", "Z"],
  },
  {
    code: "KeyX",
    type: "letter",
    ru: ["ч", "Ч"],
    en: ["x", "X"],
  },
  {
    code: "KeyC",
    type: "letter",
    ru: ["с", "С"],
    en: ["c", "C"],
  },
  {
    code: "KeyV",
    type: "letter",
    ru: ["м", "М"],
    en: ["v", "V"],
  },
  {
    code: "KeyB",
    type: "letter",
    ru: ["и", "И"],
    en: ["b", "B"],
  },
  {
    code: "KeyN",
    type: "letter",
    ru: ["т", "Т"],
    en: ["n", "N"],
  },
  {
    code: "KeyM",
    type: "letter",
    ru: ["ь", "Ь"],
    en: ["m", "M"],
  },
  {
    code: "Comma",
    type: "letter",
    ru: ["б", "Б"],
    en: [",", "<"],
  },
  {
    code: "Period",
    type: "letter",
    ru: ["ю", "Ю"],
    en: [".", ">"],
  },
  {
    code: "Slash",
    type: "letter",
    ru: [".", ","],
    en: ["/", "?"],
  },
  {
    code: "ArrowUp",
    type: "arrow",
    ru: ["▲", "▲"],
    en: ["▲", "▲"],
  },
  {
    code: "ShiftRight",
    type: "shiftRight",
    ru: ["Shift", "Shift"],
    en: ["Shift", "Shift"],
  },
  {
    code: "ControlLeft",
    type: "ctrl",
    ru: ["Ctrl", "Ctrl"],
    en: ["Ctrl", "Ctrl"],
  },
  {
    code: "MetaLeft",
    type: "win",
    lower: "Win",
    upper: "Win",
    ru: ["Win", "Win"],
    en: ["Win", "Win"],
  },
  {
    code: "AltLeft",
    type: "alt",
    ru: ["Alt", "Alt"],
    en: ["Alt", "Alt"],
  },
  {
    code: "Space",
    type: "space",
    ru: ["Space", "Space"],
    en: ["Space", "Space"],
  },
  {
    code: "AltRight",
    type: "alt",
    ru: ["Alt", "Alt"],
    en: ["Alt", "Alt"],
  },
  {
    code: "ArrowLeft",
    type: "arrow",
    ru: ["◀", "◀"],
    en: ["◀", "◀"],
  },
  {
    code: "ArrowDown",
    type: "arrow",
    ru: ["▼", "▼"],
    en: ["▼", "▼"],
  },
  {
    code: "ArrowRight",
    type: "arrow",
    ru: ["▶", "▶"],
    en: ["▶", "▶"],
  },
  {
    code: "ControlRight",
    type: "ctrl",
    ru: ["Ctrl", "Ctrl"],
    en: ["Ctrl", "Ctrl"],
  },
];
export default ruLang;
